name: ci
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          python -m pip install -r requirements.txt &&
          python -m pip install https://github.com/EdginAround/edgin_around_api/releases/download/0.0.1/edgin_around_api-0.0.1.tar.gz
      - name: Format
        run: python -m black . --config black.toml --check --verbose
      - name: Type check
        run: python -m mypy preview.py

